---
title: "Earthquake Notebook"
output: html_notebook
---
```{r}
# import libraries
library(here)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(rgl)
library(DT)
library(plotly)
library(data.table)
library(janitor)
library(ggbeeswarm)
```


```{r}
earthquakes <- read_csv(here("data", "2.5_month.csv"))
```
```{r}
eq_new <- earthquakes %>%
  separate(time, c("year", "month", "day"), remove = FALSE) %>%
  mutate(magAll = mag > mean(mag, na.rm = TRUE)) %>% # magnitudes that are greater than the average earthquakes over the last month
  group_by(magType) %>%
  # magnitude greater than the average based on the The method or algorithm used to calculate the preferred magnitude for the event
  mutate(magTypeGroup = mag > mean(mag, na.rm = TRUE)) 
  # create a column for significant earthquakes
  
select_all(eq_new)
```
```{r}
# plot magnitude levels
eq_new %>%
  ggplot(aes(x = day, y = mag)) +
  geom_point()
```
```{r}
# summarize how many earthquakes per day
eq_new %>%
  group_by(day) %>%
  summarise(obs = n())
```
```{r}
# replotting earthquakes by day using jitter0
num_colors <- 5

# Generate a color palette using RColorBrewer
color_palette <- brewer.pal(num_colors, "PuOr")

eq_new %>%
  ggplot(aes(x = day, y = mag, color = depth)) +
  geom_jitter() +
  scale_color_gradientn(colours = color_palette)
```
```{r}
# replotting earthquakes by day using jitter
num_colors <- 5

# Generate a color palette using RColorBrewer
color_palette <- brewer.pal(num_colors, "Spectral")

eq_new %>%
  ggplot(aes(x = depth, y = mag, color = depthError)) +
  geom_jitter() +
  scale_color_gradientn(colours = color_palette)
```
```{r}
# replotting earthquakes by day using quasirandom
eq_new %>%
  ggplot(aes(x = day, y = mag)) +
  geom_quasirandom()
```
```{r}
# replotting earthquakes with geom_jitter & grouped by the algorithm that detected observation 
eq_new %>%
  ggplot(aes(x = depth, y = mag, color = magType)) +
  geom_jitter() 
 
```
```{r}
# facet wrap -----------
eq_new %>%
  ggplot(aes(x = depth, y = mag, color = magType)) +
  geom_jitter() +
  facet_wrap(~ magType)
```
```{r}
color_palette <- brewer.pal(num_colors, "Spectral")

eq_new %>%
  filter(mag > 6.0 & depth < 100) %>%
  ggplot(aes(x = day, y = mag, colour = depth, size = mag)) +
  geom_point() +
  facet_wrap(~ magType) +
  scale_color_gradientn(colours = color_palette)
```
```{r}
# facet wrap -----------
eq_new %>%
  ggplot(aes(x = depth, y = mag, color = magType)) +
  geom_jitter() +
  facet_wrap(~ locationSource)
```
```{r}
eq_new %>%
  filter(locationSource == "us") %>%
  ggplot(aes(x = depth, y = mag, color = magType)) +
  geom_jitter() +
  facet_wrap(~ locationSource)
```
```{r}
spdf <- geojson_read(here("data", "shakemap.geojson"), what="sp")
df <- as.data.frame(spdf)
dfjoin <- left_join(eq_new, df, by='id')
```
```{r}
dfjoin %>%
  filter(mmi > 0) %>%
  ggplot(aes(x = depth, y = mag.x, color = mmi, size = mag.x)) +
  geom_point() +
  scale_color_distiller(palette = "YlOrBr", direction = 1)
```
```{r}
dfjoin %>%
  filter(mmi > 0) %>%
  ggplot(aes(x = depth, y = mag.x, color = mmi, size = mmi)) +
  coord_flip() +
  geom_point() +
  scale_color_distiller(palette = "YlOrBr", direction = 1) +
  geom_smooth()
```
```{r}
# correlate felt (felt) vs intensity (mmi)

dfjoin %>%
  filter(mmi > 0) %>%
  ggplot(aes(x = felt, y = mmi)) +
  geom_point()
```
```{r}
dfjoin %>%
  filter(magAll == "TRUE") %>%
  ggplot(aes(x = depth, y = mag.x, color = depthError)) +
  geom_jitter() +
  scale_color_gradientn(colours = color_palette)
```
```{r}
dfjoin %>%
  filter(mmi > 4) %>%
  ggplot(aes(x = day, y = mag, colour = depth, size = mag)) +
  geom_point() +
  scale_color_distiller(palette = "Spectral", direction = 1)
```
```