---
title: "GEOG 588 - Lesson 3"
output: html_notebook
---
### Create a story with the exoplanets data set --
##  3 Visualizations
  

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(rgl)
```
```{r}
ggplot(
  data = cleanexo, 
  mapping = aes
  (
  x = discovery_year,
  y = distance, 
  colour = mass,    
  size = mass
  )) +
  geom_point()
```
```{r}
num_colors <- 5

# Generate a color palette using RColorBrewer
color_palette <- brewer.pal(num_colors, "Spectral")

# Create your ggplot code
ggplot(
  data = cleanexo, 
  mapping = aes(
    x = discovery_year,
    y = distance, 
    colour = mass,    
    size = mass
  )
) +
  geom_jitter() + 
  scale_color_gradientn(colours = color_palette)
```
```{r}
techniquePlot <- ggplot(
  data = cleanexo, 
  mapping = aes
  (
  x = discovery_year,
  y = distance, 
  colour = mass,    
  size = mass
  )) +
  geom_jitter() + 
  scale_color_gradientn(colours = color_palette) +
  facet_wrap(~ discovery_method) +
  ggtitle(" discovery methods")

ggsave("techniquePlot.png", techniquePlot)
techniquePlot
```

```{r}
planets <- cleanexo %>%
  count(discovery_facility, sort=TRUE)
select_all(planets)
```
```{r}
discovery_count <- cleanexo %>%
  count(discovery_year, sort=TRUE) %>%
  rename(number_of_planets = n)

View(discovery_count)
```
```{r}
ggplot(
  data = discovery_count,
  mapping = aes( x = discovery_year,
                 y = number_of_planets)) + geom_line()
```
