---
title: "R Shiny web application for real-time seismic visualization – Jack Colpitt"
output: html_notebook
---
<br />

#### **Abstract --**     
    
|       Earthquakes play a pivotal role along the active tectonic boundaries of the planet. The availability of real-time data feeds is bringing a new instantaneous approach to analysis. This study suggests the creation of an R Shiny application that takes data about earthquake locations in GeoJSON format and a series of user inputs to perform spatial clustering analysis via DBSCAN. The data has a 1-minute temporal resolution and is refreshed each time the application loads. R programming packages visible in **Figure 1** will be integrated into the application to provide representation and analysis of current spatiotemporal data.There are currently a variety of web GIS (Geographical Information Systems) applications available to the public that provide point and click information and filtering to understand where and when earthquakes are happening in real time. However, R Shiny applications leveraging open web mapping that are dedicated to visualizing spatial cluster analysis of real-time geospatial data are none existant and this application aims to fill that gap. The interactive component of the Shiny application enables speedy consumption of current seismic events, as well as easy comparison of properties, and determining spatial clustering. Future research should focus on testing the effectiveness of DBSCAN for the spatial clustering of earthquake data in this type of application and on identifying new functionalities for the app users. In short, the R Shiny application will use the R programming language's capabilities and the collaborative nature of web services to instantly assess, visualize, and identify spatial clusters of current seismic events throughout the world.

```{r}
library(tidyverse) # series of packages for Data Science workflows
library(maps) # import world data
library(leaflet) # open web mapping
library(shiny) # web framework
library(DT) # DataTables
library(here) # local file directory library
library(sp) # spatial data
library(sf) # spatial data
library(rgdal) # read geojson web services
library(lubridate) # parse timestamp observations
library(shiny.telemetry) # read user inputs for the application and store in a local sqlite3 database
library(leaflet.extras) # create geometries in the web map
library(dbscan) # density based spatial clustering tool
library(factoextra) # render the spatial clusters
library(mapboxapi) # import tiles from mapbox
library(RColorBrewer) # symbology for circle markers in leaflet
library(basemaps) # import basemaps
library(plotly) # interactive plots
library(shinyjqui) # make tables and html elements draggable and resizeable
```

**Figure 1.** R Packages used in the USGS Earthquakes - Real Time Data application. The list of packages was compiled to assist in data extraction, manipulation, visualization, and web based functionality.

<br />

#### **Introduction --** 

|       Web applications allow for the distribution of information and analysis to end users in real time. In contrast, desktop-based analysis software can cause limitations and barriers to entry based on distribution hurdles and programming dependencies. This study's objective is to create an R Shiny application that makes analysis of real-time earthquake data from the USGS (US Geological Survey) accessible to a variety of users. Notably, users that interested in visualizing and identifying spatial clusters in the data. The application will use DBSCAN as the spatial clustering method, which finds clusters of points that are in close proximity based on a specified search distance (Density-based Clustering (Spatial Statistics); ArcGIS Pro | Documentation, n.d.).

<br />

##### **R Shiny Web Framework**

|       Shiny is an R package and web framework that allows you to easily create rich, interactive web apps. Shiny allows you to take your work in R and expose it via a web browser so that anyone can use it (Hadley Wickham, 2021). Shiny apps are contained in a single script called app.R. The script app.R lives in a directory (for example, newdir/) and the app can be run with runApp("newdir") (Shiny - Welcome to Shiny, n.d.).
<br />
app.R has three components:

* a user interface object

* a server function

* a call to the shinyApp function

(Shiny - Welcome to Shiny, n.d.)
        
##### **Density-based spatial clustering of applications with noise (DBSCAN)**





#### **Resources**

Density-based Clustering (Spatial Statistics) ;ArcGIS Pro | Documentation. https://pro.arcgis.com/en/pro-app/latest/tool-reference/spatial-statistics/densitybasedclustering.htm

Hadley Wickham. (2021). Mastering shiny. O’Reilly Media, Inc.  

Shiny - Welcome to Shiny. (n.d.). Shiny - Welcome to Shiny. https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html